services:
    portfolio-frontend:
        build: .
        ports:
            - "3000:3000"
        network_mode: "host"
        environment:
            - PORT=3000
            - HOSTNAME=0.0.0.0
        restart: unless-stopped
